# Generated by Django 3.0.3 on 2020-04-08 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField()),
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank='True', upload_to='bookpics')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
