# Generated by Django 3.0.5 on 2020-04-09 09:51

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200408_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='json',
            field=jsonfield.fields.JSONField(default={'reviews': {}, 'tags': {}}),
        ),
    ]
